# Generated by Django 4.2.5 on 2023-10-10 08:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_blog_image_alter_blog_posted_alter_comment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        unique_for_date="Catalogdate", verbose_name="Название курса"
                    ),
                ),
                (
                    "Catalogdate",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(2023, 10, 10, 8, 25, 34, 432427),
                        verbose_name="Дата создания",
                    ),
                ),
                ("description", models.TextField(verbose_name="Краткое содержание")),
                (
                    "image",
                    models.FileField(
                        default="temp.jpg", upload_to="", verbose_name="Путь к картинке"
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент каталога",
                "verbose_name_plural": "Элемент каталога",
                "db_table": "CatalogItems",
                "ordering": ["-Catalogdate"],
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 10, 10, 8, 25, 34, 430950),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор Комментария",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 10, 10, 8, 25, 34, 431676),
                verbose_name="Дата комментария",
            ),
        ),
    ]
