# Generated by Django 4.2.5 on 2023-10-24 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_catalogitem_alter_blog_posted_alter_comment_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="cost",
            field=models.IntegerField(default="5000", verbose_name="Стоимость курса"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 10, 24, 7, 58, 56, 47185),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="Catalogdate",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 10, 24, 7, 58, 56, 48006),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 10, 24, 7, 58, 56, 47612),
                verbose_name="Дата комментария",
            ),
        ),
        migrations.CreateModel(
            name="Backet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментарий")),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(2023, 10, 24, 7, 58, 56, 48335),
                        verbose_name="Дата добавления в корзину",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.catalogitem",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
                "db_table": "Backet",
                "ordering": ["-date"],
            },
        ),
    ]
