# Generated by Django 4.2.5 on 2023-11-28 05:55

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_backet_date_alter_blog_posted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backet",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 5, 55, 1, 506084),
                verbose_name="Дата добавления в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="backet",
            name="user",
            field=models.TextField(default=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 5, 55, 1, 504026),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="Catalogdate",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 5, 55, 1, 505465),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 5, 55, 1, 504789),
                verbose_name="Дата комментария",
            ),
        ),
    ]
