# Generated by Django 4.2.5 on 2023-11-28 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_backet_date_alter_blog_posted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backet",
            name="course",
        ),
        migrations.RemoveField(
            model_name="backet",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="backet",
            name="user",
        ),
        migrations.AlterField(
            model_name="backet",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 5, 59, 253810),
                verbose_name="Дата добавления в корзину",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 5, 59, 251909),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="Catalogdate",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 5, 59, 253196),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 5, 59, 252581),
                verbose_name="Дата комментария",
            ),
        ),
    ]
