# Generated by Django 4.2.5 on 2023-11-28 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_remove_backet_course_remove_backet_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backet",
            options={
                "ordering": ["-id"],
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
        migrations.RemoveField(
            model_name="backet",
            name="date",
        ),
        migrations.AlterField(
            model_name="blog",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 6, 50, 105903),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="Catalogdate",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 6, 50, 107036),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 11, 28, 6, 6, 50, 106495),
                verbose_name="Дата комментария",
            ),
        ),
    ]
